on unload:
    loop {oxidizer.location::*}:
        set {_n1} to 0
        loop (0, 9, 18, 27, 12, and 16):
            add 1 to {_n1}
            set {oxidizer.save::%loop-value-1%::%{_n1}%} to slot loop-value-2 of gui with id "ElectricOxidizer.%loop-value-1%"

on load:
    loop {oxidizer.location::*}:
        if gui with id "ElectricOxidizer.%loop-value%" is not set:
            create a gui with id "ElectricOxidizer.%loop-value%" with virtual chest inventory with 4 rows named "Electric Oxidizer" with shape "1wyyybooo" and "2wy3ybo4o" and "5wyyybooo" and "6wbbbbbbb":
                set {_n1} to 0
                loop 6 times:
                    add 1 to {_n1}
                    set {_n4::*} to 0, 9, 18, 27, 12, and 16
                    if {oxidizer.save::%loop-value-1%::%{_n1}%} is not set:
                        make gui slot {_n4::%{_n1}%} with moveable air
                    if {oxidizer.save::%loop-value-1%::%{_n1}%} is air:
                        make gui slot {_n4::%{_n1}%} with moveable air
                    else:
                        make gui slot {_n4::%{_n1}%} with moveable {oxidizer.save::%loop-value-1%::%{_n1}%}
                make gui slot "w" with white stained glass pane named "&fMachine Modifiers"
                make gui slot "y" with blue stained glass pane named "&9Input"
                make gui slot "o" with lime stained glass pane named "&aOutput"
                make gui slot "b" with gray stained glass pane named " "

on place of copper block:
    if nbt of player's held item contain "CheesyCraft:""ElectricOxidizer""":
        set {oxidizer.place::%event-block's location%} to true
        set {oxidizer.location::%event-block's location%} to event-block's location

on break of copper block or exposed copper or weathered copper or oxidized copper:
    if {oxidizer.place::%event-block's location%} is true:
        cancel the drops
        clear {oxidizer.place::%event-block's location%}
        clear {oxidizer.location::%event-block's location%}
        drop {saveditems::ElectricOxidizer}
        loop all items in gui with id "ElectricOxidizer.%event-block's location%":
            if index of loop-item is 0 or 9 or 27 or 18 or 12 or 16:
                drop loop-item
        delete gui with id "ElectricOxidizer.%event-block's location%"
        
on right click:
    if player is not sneaking:
        if event-player can build at location of event-block:
            if {oxidizer.place::%event-block's location%} is true:
                cancel event
                if gui with id "ElectricOxidizer.%event-block's location%" is not set:
                    create a gui with id "ElectricOxidizer.%event-block's location%" with virtual chest inventory with 4 rows named "Electric Oxidizer" with shape "xwyyybooo" and "xwyxyboxo" and "xwyyybooo" and "xwbbbbbbb":
                        make gui slot "x" with moveable air
                        make gui slot "w" with white stained glass pane named "&fMachine Modifiers"
                        make gui slot "y" with blue stained glass pane named "&9Input"
                        make gui slot "o" with lime stained glass pane named "&aOutput"
                        make gui slot "b" with gray stained glass pane named " "
                open gui with id "ElectricOxidizer.%event-block's location%" to player
                while name of player's current inventory contains "Electric Oxidizer":
                    if event-block is air:
                        close player's inventory
                    wait 1 tick
            

every 1 second:
    loop {oxidizer.location::*}:
        if chunk at loop-value is loaded:
            if {oxidizer.maxed::%loop-value%} is true:
                continue loop
            loop 28 times:
                set {_n} to loop-number - 1
                if {_n} is 0 or 9 or 27 or 18:
                    if nbt of slot {_n} of gui with id "ElectricOxidizer.%loop-value-1%" contains "RedstoneSwitchMod":
                        if check [block at loop-value-1 is not redstone powered]->[block at loop-value-1 is not indirectly redstone powered]:
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 exposed copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 weathered copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    chance of 5%:
                                                        if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                            add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            add -3 to {powerbank.power::%loop-value-3%}
                                                            set {oxidixer.activated::%loop-value-1%} to true
                                                            set {oxidixer.activated2::%loop-value-1%} to true
                                                            exit 2 loops
                                                    add 1 oxidized copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified cut copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed cut copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 exposed cut copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed cut copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered cut copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 weathered cut copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered cut copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized cut copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    chance of 5%:
                                                        if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                            add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            add -3 to {powerbank.power::%loop-value-3%}
                                                            set {oxidixer.activated::%loop-value-1%} to true
                                                            set {oxidixer.activated2::%loop-value-1%} to true
                                                            exit 2 loops
                                                    add 1 oxidized cut copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified cut copper slab:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed copper slab:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 exposed copper slab to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed copper slab:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered copper slab:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 weathered copper slab to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered copper slab:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized copper slab:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    chance of 5%:
                                                        if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                            add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            add -3 to {powerbank.power::%loop-value-3%}
                                                            set {oxidixer.activated::%loop-value-1%} to true
                                                            set {oxidixer.activated2::%loop-value-1%} to true
                                                            exit 2 loops
                                                    add 1 oxidized copper slab to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified cut copper stairs:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed copper stairs:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 exposed copper stairs to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed copper stairs:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered copper stairs:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 weathered copper stairs to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered copper stairs:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized copper stairs:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    chance of 5%:
                                                        if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                            add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            add -3 to {powerbank.power::%loop-value-3%}
                                                            set {oxidixer.activated::%loop-value-1%} to true
                                                            set {oxidixer.activated2::%loop-value-1%} to true
                                                            exit 2 loops
                                                    add 1 oxidized copper stairs to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                    else if nbt of slot {_n} of gui with id "ElectricOxidizer.%loop-value-1%" contains "RedstoneActivationMod":
                        if block at loop-value-1 is redstone powered:
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 exposed copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 weathered copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    chance of 5%:
                                                        if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                            add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            add -3 to {powerbank.power::%loop-value-3%}
                                                            set {oxidixer.activated::%loop-value-1%} to true
                                                            set {oxidixer.activated2::%loop-value-1%} to true
                                                            exit 2 loops
                                                    add 1 oxidized copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified cut copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed cut copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 exposed cut copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed cut copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered cut copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 weathered cut copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered cut copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized cut copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    chance of 5%:
                                                        if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                            add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            add -3 to {powerbank.power::%loop-value-3%}
                                                            set {oxidixer.activated::%loop-value-1%} to true
                                                            set {oxidixer.activated2::%loop-value-1%} to true
                                                            exit 2 loops
                                                    add 1 oxidized cut copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified cut copper slab:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed copper slab:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 exposed copper slab to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed copper slab:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered copper slab:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 weathered copper slab to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered copper slab:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized copper slab:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    chance of 5%:
                                                        if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                            add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            add -3 to {powerbank.power::%loop-value-3%}
                                                            set {oxidixer.activated::%loop-value-1%} to true
                                                            set {oxidixer.activated2::%loop-value-1%} to true
                                                            exit 2 loops
                                                    add 1 oxidized copper slab to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified cut copper stairs:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed copper stairs:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 exposed copper stairs to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed copper stairs:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered copper stairs:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 weathered copper stairs to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered copper stairs:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized copper stairs:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    chance of 5%:
                                                        if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                            add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            add -3 to {powerbank.power::%loop-value-3%}
                                                            set {oxidixer.activated::%loop-value-1%} to true
                                                            set {oxidixer.activated2::%loop-value-1%} to true
                                                            exit 2 loops
                                                    add 1 oxidized copper stairs to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                        if block at loop-value-1 is indirectly redstone powered:
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 exposed copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 weathered copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    chance of 5%:
                                                        if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                            add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            add -3 to {powerbank.power::%loop-value-3%}
                                                            set {oxidixer.activated::%loop-value-1%} to true
                                                            set {oxidixer.activated2::%loop-value-1%} to true
                                                            exit 2 loops
                                                    add 1 oxidized copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified cut copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed cut copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 exposed cut copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed cut copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered cut copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 weathered cut copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered cut copper block:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized cut copper block:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    chance of 5%:
                                                        if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                            add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            add -3 to {powerbank.power::%loop-value-3%}
                                                            set {oxidixer.activated::%loop-value-1%} to true
                                                            set {oxidixer.activated2::%loop-value-1%} to true
                                                            exit 2 loops
                                                    add 1 oxidized cut copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified cut copper slab:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed copper slab:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 exposed copper slab to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed copper slab:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered copper slab:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 weathered copper slab to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered copper slab:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized copper slab:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    chance of 5%:
                                                        if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                            add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            add -3 to {powerbank.power::%loop-value-3%}
                                                            set {oxidixer.activated::%loop-value-1%} to true
                                                            set {oxidixer.activated2::%loop-value-1%} to true
                                                            exit 2 loops
                                                    add 1 oxidized copper slab to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified cut copper stairs:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed copper stairs:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 exposed copper stairs to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed copper stairs:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered copper stairs:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    add 1 weathered copper stairs to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered copper stairs:
                                if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized copper stairs:
                                    if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                        loop {powerbank.location::*}:
                                            set {_c1::*} to region at loop-value-1
                                            set {_c2::*} to region at loop-value-3
                                            if {_c1::*} is not {_c2::*}:
                                                continue
                                            if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                                if {powerbank.power::%loop-value-3%} >= 3:
                                                    chance of 5%:
                                                        if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                            add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                            add -3 to {powerbank.power::%loop-value-3%}
                                                            set {oxidixer.activated::%loop-value-1%} to true
                                                            set {oxidixer.activated2::%loop-value-1%} to true
                                                            exit 2 loops
                                                    add 1 oxidized copper stairs to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                    add -3 to {powerbank.power::%loop-value-3%}
                                                    set {oxidixer.activated::%loop-value-1%} to true
                                                    set {oxidixer.activated2::%loop-value-1%} to true
                                                    exit 2 loops
                        exit loop
                    else:
                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified copper block:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed copper block:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                    loop {powerbank.location::*}:
                                        set {_c1::*} to region at loop-value-1
                                        set {_c2::*} to region at loop-value-3
                                        if {_c1::*} is not {_c2::*}:
                                            continue
                                        if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                            if {powerbank.power::%loop-value-3%} >= 3:
                                                add 1 exposed copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                add -3 to {powerbank.power::%loop-value-3%}
                                                set {oxidixer.activated::%loop-value-1%} to true
                                                set {oxidixer.activated2::%loop-value-1%} to true
                                                exit 2 loops
                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed copper block:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered copper block:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                    loop {powerbank.location::*}:
                                        set {_c1::*} to region at loop-value-1
                                        set {_c2::*} to region at loop-value-3
                                        if {_c1::*} is not {_c2::*}:
                                            continue
                                        if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                            if {powerbank.power::%loop-value-3%} >= 3:
                                                add 1 weathered copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                add -3 to {powerbank.power::%loop-value-3%}
                                                set {oxidixer.activated::%loop-value-1%} to true
                                                set {oxidixer.activated2::%loop-value-1%} to true
                                                exit 2 loops
                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered copper block:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized copper block:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                    loop {powerbank.location::*}:
                                        set {_c1::*} to region at loop-value-1
                                        set {_c2::*} to region at loop-value-3
                                        if {_c1::*} is not {_c2::*}:
                                            continue
                                        if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                            if {powerbank.power::%loop-value-3%} >= 3:
                                                chance of 5%:
                                                    if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                        add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                        remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                        add -3 to {powerbank.power::%loop-value-3%}
                                                        set {oxidixer.activated::%loop-value-1%} to true
                                                        set {oxidixer.activated2::%loop-value-1%} to true
                                                        exit 2 loops
                                                add 1 oxidized copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                add -3 to {powerbank.power::%loop-value-3%}
                                                set {oxidixer.activated::%loop-value-1%} to true
                                                set {oxidixer.activated2::%loop-value-1%} to true
                                                exit 2 loops
                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified cut copper block:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed cut copper block:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                    loop {powerbank.location::*}:
                                        set {_c1::*} to region at loop-value-1
                                        set {_c2::*} to region at loop-value-3
                                        if {_c1::*} is not {_c2::*}:
                                            continue
                                        if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                            if {powerbank.power::%loop-value-3%} >= 3:
                                                add 1 exposed cut copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                add -3 to {powerbank.power::%loop-value-3%}
                                                set {oxidixer.activated::%loop-value-1%} to true
                                                set {oxidixer.activated2::%loop-value-1%} to true
                                                exit 2 loops
                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed cut copper block:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered cut copper block:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                    loop {powerbank.location::*}:
                                        set {_c1::*} to region at loop-value-1
                                        set {_c2::*} to region at loop-value-3
                                        if {_c1::*} is not {_c2::*}:
                                            continue
                                        if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                            if {powerbank.power::%loop-value-3%} >= 3:
                                                add 1 weathered cut copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                add -3 to {powerbank.power::%loop-value-3%}
                                                set {oxidixer.activated::%loop-value-1%} to true
                                                set {oxidixer.activated2::%loop-value-1%} to true
                                                exit 2 loops
                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered cut copper block:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized cut copper block:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                    loop {powerbank.location::*}:
                                        set {_c1::*} to region at loop-value-1
                                        set {_c2::*} to region at loop-value-3
                                        if {_c1::*} is not {_c2::*}:
                                            continue
                                        if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                            if {powerbank.power::%loop-value-3%} >= 3:
                                                chance of 5%:
                                                    if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                        add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                        remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                        add -3 to {powerbank.power::%loop-value-3%}
                                                        set {oxidixer.activated::%loop-value-1%} to true
                                                        set {oxidixer.activated2::%loop-value-1%} to true
                                                        exit 2 loops
                                                add 1 oxidized cut copper block to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                add -3 to {powerbank.power::%loop-value-3%}
                                                set {oxidixer.activated::%loop-value-1%} to true
                                                set {oxidixer.activated2::%loop-value-1%} to true
                                                exit 2 loops
                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified cut copper slab:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed copper slab:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                    loop {powerbank.location::*}:
                                        set {_c1::*} to region at loop-value-1
                                        set {_c2::*} to region at loop-value-3
                                        if {_c1::*} is not {_c2::*}:
                                            continue
                                        if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                            if {powerbank.power::%loop-value-3%} >= 3:
                                                add 1 exposed copper slab to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                add -3 to {powerbank.power::%loop-value-3%}
                                                set {oxidixer.activated::%loop-value-1%} to true
                                                set {oxidixer.activated2::%loop-value-1%} to true
                                                exit 2 loops
                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed copper slab:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered copper slab:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                    loop {powerbank.location::*}:
                                        set {_c1::*} to region at loop-value-1
                                        set {_c2::*} to region at loop-value-3
                                        if {_c1::*} is not {_c2::*}:
                                            continue
                                        if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                            if {powerbank.power::%loop-value-3%} >= 3:
                                                add 1 weathered copper slab to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                add -3 to {powerbank.power::%loop-value-3%}
                                                set {oxidixer.activated::%loop-value-1%} to true
                                                set {oxidixer.activated2::%loop-value-1%} to true
                                                exit 2 loops
                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered copper slab:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized copper slab:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                    loop {powerbank.location::*}:
                                        set {_c1::*} to region at loop-value-1
                                        set {_c2::*} to region at loop-value-3
                                        if {_c1::*} is not {_c2::*}:
                                            continue
                                        if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                            if {powerbank.power::%loop-value-3%} >= 3:
                                                chance of 5%:
                                                    if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                        add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                        remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                        add -3 to {powerbank.power::%loop-value-3%}
                                                        set {oxidixer.activated::%loop-value-1%} to true
                                                        set {oxidixer.activated2::%loop-value-1%} to true
                                                        exit 2 loops
                                                add 1 oxidized copper slab to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                add -3 to {powerbank.power::%loop-value-3%}
                                                set {oxidixer.activated::%loop-value-1%} to true
                                                set {oxidixer.activated2::%loop-value-1%} to true
                                                exit 2 loops
                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified cut copper stairs:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or exposed copper stairs:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                    loop {powerbank.location::*}:
                                        set {_c1::*} to region at loop-value-1
                                        set {_c2::*} to region at loop-value-3
                                        if {_c1::*} is not {_c2::*}:
                                            continue
                                        if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                            if {powerbank.power::%loop-value-3%} >= 3:
                                                add 1 exposed copper stairs to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                add -3 to {powerbank.power::%loop-value-3%}
                                                set {oxidixer.activated::%loop-value-1%} to true
                                                set {oxidixer.activated2::%loop-value-1%} to true
                                                exit 2 loops
                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified exposed copper stairs:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or weathered copper stairs:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                    loop {powerbank.location::*}:
                                        set {_c1::*} to region at loop-value-1
                                        set {_c2::*} to region at loop-value-3
                                        if {_c1::*} is not {_c2::*}:
                                            continue
                                        if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                            if {powerbank.power::%loop-value-3%} >= 3:
                                                add 1 weathered copper stairs to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                add -3 to {powerbank.power::%loop-value-3%}
                                                set {oxidixer.activated::%loop-value-1%} to true
                                                set {oxidixer.activated2::%loop-value-1%} to true
                                                exit 2 loops
                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is unmodified weathered copper stairs:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air or oxidized copper stairs:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" < 64:
                                    loop {powerbank.location::*}:
                                        set {_c1::*} to region at loop-value-1
                                        set {_c2::*} to region at loop-value-3
                                        if {_c1::*} is not {_c2::*}:
                                            continue
                                        if distance between loop-value-1 and loop-value-3 <= {powerbank.range::%loop-value-3%}:
                                            if {powerbank.power::%loop-value-3%} >= 3:
                                                chance of 5%:
                                                    if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                        add {saveditems::MysticalPatina} to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                        remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                        add -3 to {powerbank.power::%loop-value-3%}
                                                        set {oxidixer.activated::%loop-value-1%} to true
                                                        set {oxidixer.activated2::%loop-value-1%} to true
                                                        exit 2 loops
                                                add 1 oxidized copper stairs to slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                remove 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" from slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                add -3 to {powerbank.power::%loop-value-3%}
                                                set {oxidixer.activated::%loop-value-1%} to true
                                                set {oxidixer.activated2::%loop-value-1%} to true
                                                exit 2 loops
            
every 1 second:
    loop {oxidizer.location::*}:
        if chunk at loop-value is loaded:
            loop 28 times:
                set {_n} to loop-number - 1
                if {_n} is 0 or 9 or 27 or 18:
                    if nbt of slot {_n} of gui with id "ElectricOxidizer.%loop-value-1%" contains "CheesyCraft:""FunnelMod""":
                        if block above loop-value-1 is hopper:
                            if block data tag "facing" of block above loop-value-1 is "down":
                                loop all items in inventory of block above loop-value-1:
                                    if item amount of loop-value-3 = max stack size of 1 of loop-value-3:
                                        if 1 of loop-value-3 is copper block or exposed copper or weathered copper or cut copper block or exposed cut copper block or weathered cut copper block or exposed copper stairs or weathered copper stairs or cut copper stairs or cut copper slab or exposed copper slab or weathered copper slab:
                                            if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                                set {_i} to item amount of loop-value-3 of loop-value-3
                                                remove {_i} from loop-value-3
                                                add {_i} to slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                exit loop
                        if block below loop-value-1 is hopper:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is not air:
                                if item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" = max stack size of 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%":
                                    if block below loop-value-1 can hold 1 of slot 41 of gui with id "ElectricOxidizer.%loop-value-1%":
                                        set {_i} to item amount of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                        remove {_i} from slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                        add {_i} to inventory of block below loop-value-1
                                    
every 2 ticks:
    loop {oxidizer.location::*}:
        if {oxidizer.activated::%loop-value%} is true:
            if chunk at loop-value is loaded:
                loop 28 times:
                    set {_n} to loop-number - 1
                    if {_n} is 0 or 9 or 18 or 27:
                        if nbt of slot {_n} of gui with id "ElectricOxidizer.%loop-value-1%" contains "CheesyCraft:""EcholomaticMod""":
                            loop all blocks in radius 9 of loop-value-1:
                                if loop-value-3 is sculk sensor:
                                    spawn snowball at location of loop-value-3
                            delete {oxidizer.activated::%loop-value-1%}
                            exit loop
                                           
every 2 ticks:
    loop {oxidizer.location::*}:
        if chunk at loop-value is loaded:
            loop 28 times:
                set {_n} to loop-number - 1
                if {_n} is 0 or 9 or 18 or 27:
                    if nbt of slot {_n} of gui with id "ElectricOxidizer.%loop-value-1%" contains "CheesyCraft:""WardstaticMod""":
                        set {_total} to tag "Total" of nbt of slot {_n} of gui with id "ElectricOxidizer.%loop-value-1%"
                        set {_max} to tag "Max" of nbt of slot {_n} of gui with id "ElectricOxidizer.%loop-value-1%"
                        if {_total} = {_max}:
                            set {oxidizer.maxed::%loop-value-1%} to true
                        if {_total} < {_max}:
                            if {oxidizer.activated2::%loop-value-1%} is true:
                                add "{Total:%{_total} + 1%}" to nbt of slot {_n} of gui with id "ElectricOxidizer.%loop-value-1%"
                        loop all blocks in radius 1 of loop-value-1:
                            if loop-value-3 is sculk:
                                delete {oxidizer.maxed::%loop-value-1%}
                                add "{Total:0}" to nbt of slot {_n} of gui with id "ElectricOxidizer.%loop-value-1%"
                        delete {oxidizer.activated2::%loop-value-1%}
                
every 2 ticks:
    loop {oxidizer.location::*}:
        if nbt of slot 0 of gui with id "ElectricOxidizer.%loop-value%" contains "CheesyCraft:""WardstaticMod""":
            set {_total} to tag "Total" of nbt of slot 0 of gui with id "ElectricOxidizer.%loop-value%"
            set {_max} to tag "Max" of nbt of slot 0 of gui with id "ElectricOxidizer.%loop-value%"
            if {_total} = {_max}:
                continue loop
        if nbt of slot 9 of gui with id "ElectricOxidizer.%loop-value%" contains "CheesyCraft:""WardstaticMod""":
            set {_total} to tag "Total" of nbt of slot 9 of gui with id "ElectricOxidizer.%loop-value%"
            set {_max} to tag "Max" of nbt of slot 9 of gui with id "ElectricOxidizer.%loop-value%"
            if {_total} = {_max}:
                continue loop
        if nbt of slot 18 of gui with id "ElectricOxidizer.%loop-value%" contains "CheesyCraft:""WardstaticMod""":
            set {_total} to tag "Total" of nbt of slot 18 of gui with id "ElectricOxidizer.%loop-value%"
            set {_max} to tag "Max" of nbt of slot 18 of gui with id "ElectricOxidizer.%loop-value%"
            if {_total} = {_max}:
                continue loop
        if nbt of slot 27 of gui with id "ElectricOxidizer.%loop-value%" contains "CheesyCraft:""WardstaticMod""":
            set {_total} to tag "Total" of nbt of slot 27 of gui with id "ElectricOxidizer.%loop-value%"
            set {_max} to tag "Max" of nbt of slot 27 of gui with id "ElectricOxidizer.%loop-value%"
            if {_total} = {_max}:
                continue loop
        delete {oxidizer.maxed::%loop-value%}
                            
every 1 second:
    loop {oxidizer.location::*}:
        if chunk at loop-value is loaded:
            loop 28 times:
                set {_n} to loop-number - 1
                if {_n} is 0 or 9 or 27 or 18:
                    if nbt of slot {_n} of gui with id "ElectricOxidizer.%loop-value-1%" contains "CheesyCraft:""HopperMod""":
                        if block above loop-value-1 is hopper:
                            if block data tag "facing" of block above loop-value-1 is "down":
                                loop all items in inventory of block above loop-value-1:
                                    if 1 of loop-value-3 is copper block or exposed copper or weathered copper or cut copper block or exposed cut copper block or weathered cut copper block or exposed copper stairs or weathered copper stairs or cut copper stairs or cut copper slab or exposed copper slab or weathered copper slab:
                                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is air:
                                            set {_i} to 1 of loop-value-3
                                            remove 1 of loop-value-3 from loop-value-3
                                            add {_i} to slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                            exit loop
                                        if 1 of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" is 1 of loop-value-3:
                                            if item amount of slot 12 of gui with id "ElectricOxidizer.%loop-value-1%" < max stack size of 1 of loop-value-3:
                                                set {_i} to 1 of loop-value-3
                                                remove 1 of loop-value-3 from loop-value-3
                                                add {_i} to slot 12 of gui with id "ElectricOxidizer.%loop-value-1%"
                                                exit loop
                        if block below loop-value-1 is hopper:
                            if 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%" is not air:
                                if block below loop-value-1 can hold 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%":
                                    set {_i} to 1 of slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                    remove {_i} from slot 16 of gui with id "ElectricOxidizer.%loop-value-1%"
                                    add {_i} to inventory of block below loop-value-1